#!/bin/bash
VERSION=`git describe --tags | sed 's|-\(.*\)-.*|.\1|'`
VERSION="${VERSION:1}"
echo "Inferred version: $VERSION"
echo "Checking configure await..."
if ! ./checkConfigureAwait; then
    exit 1
fi
sed "s|<version>.*</version>|<version>$VERSION</version>|" Qlik.OAuthManager.nuspec.template > Qlik.OAuthManager.nuspec
sed "s|@VERSION|$VERSION|g" SystemConstants.template > src/Qlik.OAuthManager/Qlik.OAuthManager/SystemConstants.cs
sed "s|@VERSION|$VERSION|g" VersionAssemblyInfo.template > src/Qlik.OAuthManager/Qlik.OAuthManager/VersionAssemblyInfo.cs
nuget restore src/Qlik.OAuthManager/
build.bat
mkNugetPkg
